### ISSUE TITLE
Senha exposta 

### ISSUE THREAD

**Issue by joaosantosg** [let-lucasOliveira/Projetos#1]
### Issue: Solicitação de Remoção de Arquivo de Senha do Repositório

**Descrição:**
Atualmente, seu repositório contém um arquivo de senha que representa um grave risco de segurança. A presença desse arquivo expõe suas credenciais sensíveis, como a senha de aplicativo Google, a acessos não autorizados e comprometimento de dados sensíveis. É imperativo que você remova esse arquivo imediatamente para proteger a integridade e segurança do seu projeto.

**Solicitação:**
Solicitamos a remoção do arquivo de senha do seu repositório. Além disso, propomos a implementação de um sistema de armazenamento seguro de credenciais, onde as informações sensíveis serão armazenadas em um arquivo de configuração `.env`, seguindo as melhores práticas de segurança.

**Ações Propostas:**
1. Remoção do arquivo de senha do repositório.
2. Implementação de um sistema de armazenamento seguro de credenciais, utilizando o arquivo `.env`.
3. Atualização das credenciais sensíveis, como a senha de aplicativo Google, seguindo as práticas recomendadas.

**Benefícios Esperados:**
- Redução significativa dos riscos de acesso não autorizado e violações de segurança.
- Conformidade com regulamentações de privacidade de dados e padrões de segurança.
- Proteção da integridade e confidencialidade das suas credenciais sensíveis.

**Contexto Adicional:**
A exposição de credenciais sensíveis no repositório representa uma ameaça séria à segurança do seu projeto. A remoção imediata desse arquivo e a implementação de medidas de segurança adequadas são essenciais para mitigar esses riscos e proteger seus dados contra acessos não autorizados.

**Comment by let-lucasOliveira** [comment]
Olá, João, uma boa noite!
Gostaria de agradecer pelo feedback e por sua importante observação. Irei realizar os reparos sugeridos, para te tranquilizar, também, gostaria de deixá-lo ciente de que tanto o e-mail quanto a senha dos arquivos em python (que acredito que foi o que te levou a comentar sobre os cuidados que são de extrema importância) são fictícios, não havendo uma conta real com essas informações.

Quanto à sugestão da extensão mais segura para se deixar os arquivos, eu realmente não estava ciente disto e irei implementar, muito obrigado mais uma vez por ter dedicado um tempo ao meu repositório!
